### ISSUE TITLE
Level Selection + Character Selection Integration

### ISSUE THREAD

**Issue by ultraflame4** [ultraflame4/MSO_RecycleRight#109]
## Tasks
- [x] Basic Level Selection
- [x] Train Door Transition
- [x] Level Selection Map
    - [x] Map is scrollable
    - [x] Clicking on station shows a small preview popup
- [x] Level View Scene _(Inside Train)_
    - [x] Level Description
    - [x] Start Button
    - [x] Character Selection Button
- [x] Character Selection
    - [x] Transition to Character Selection
    - [x] Character description menu over train window
    - [x] Able to select character and place on seat
    - [x] Selected characters transfer to levels
