### ISSUE TITLE
Bins & related entities

### ISSUE THREAD

**Issue by ultraflame4** [ultraflame4/MSO_RecycleRight#16]
- [x] Create Bins (prefab and stuff)
- [x] Interaction with recyclables
   - [x] #24
   - [x] Interaction with player (knockback) (related #15 )
- [x] Interaction with contaminants (see https://github.com/ultraflame4/MSO_RecycleRight/issues/17 )
   - [x] Create contaminants (see #17 )
   - [x] Infested type contaminants (see #23 )
- [x] Bin cleaning #48 
- [x] #77
